# -*- coding: utf-8 -*-
"""graphs_BiCGSTAB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JjbKA6yOy6povoj17_u_jvJPtc-GEcHZ
"""

import pandas as pd
import matplotlib.pyplot as plt

file_path = 'data.csv'
data = pd.read_csv(file_path)

data['Size'] = pd.to_numeric(data['Size'], errors='coerce')

plt.figure(figsize=(10, 6))
plt.plot(data['Size'], data['Parallel BiCGStab (2CORES)'], label='Parallel BiCGStab (2 Cores)', marker='o', linestyle='-', color='blue')
plt.plot(data['Size'], data['Eigen BiCGStab (2CORES)'], label='Eigen BiCGStab (2 Cores)', marker='o', linestyle='--', color='green')
plt.plot(data['Size'], data['Sequential BiCGStab'], label='Sequential BiCGStab', marker='s', linestyle=':', color='purple')

plt.title('Performance Comparison (2 Cores)')
plt.xlabel('Matrix Size')
plt.ylabel('Execution Time (s)')
plt.legend()
plt.grid(False)

plt.xticks(data['Size'], rotation=45)

plt.yticks(range(0, 101, 10))
plt.savefig('performance_2cores_plot.png')
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(data['Size'], data['Parallel BiCGStab (4CORES)'], label='Parallel BiCGStab (4 Cores)', marker='x', linestyle='-', color='red')
plt.plot(data['Size'], data['Eigen BiCGStab (4CORES)'], label='Eigen BiCGStab (4 Cores)', marker='x', linestyle='--', color='orange')
plt.plot(data['Size'], data['Sequential BiCGStab'], label='Sequential BiCGStab', marker='s', linestyle=':', color='purple')

plt.title('Performance Comparison (4 Cores)')
plt.xlabel('Matrix Size')
plt.ylabel('Execution Time (s)')
plt.legend()
plt.grid(False)

plt.xticks(data['Size'], rotation=45)

plt.yticks(range(0, 90, 10))

plt.savefig('performance_4cores_plot.png')
plt.show()